In [1]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import importlib

In [3]:
# import classes
import classes.data_quality_analyzer
importlib.reload(classes.data_quality_analyzer)

from classes.data_quality_analyzer import DataQualityAnalyzer
from classes.data_info_display import DataInfoDisplay

In [4]:
E = pd.read_csv('datasets/employees.csv')
HR_E = pd.read_csv('datasets/hr_events.csv')
P = pd.read_csv('datasets/performance_records.csv')
TE = pd.read_csv('datasets/training_enrollments.csv')
TP = pd.read_csv('datasets/training_programs.csv')

### Cleaning data (employees dataset)

In [5]:
data_display = DataInfoDisplay(data=E)   
data_display.display()

                                    Data Info
╭──────────────────────────────┬──────────┬────────┬─────────┬──────────────────╮
│ Column                       │ Non-Null │ Unique │  Dtype  │ Sample           │
├──────────────────────────────┼──────────┼────────┼─────────┼──────────────────┤
│ employee_id                  │  3,500   │ 3,500  │ object  │ EMP00001         │
│ department                   │  3,500   │   4    │ object  │ Customer Support │
│ country                      │  3,500   │   6    │ object  │ Germany          │
│ job_level                    │  3,500   │   6    │ object  │ Team Lead        │
│ gender                       │  3,413   │   3    │ object  │ Female           │
│ age                          │  3,500   │   25   │  int64  │ 26               │
│ hire_date                    │  3,500   │ 1,939  │ object  │ 2024-05-04       │
│ tenure_days_as_of_2025_06_30 │  3,500   │ 1,939  │  int64  │ 422              │
│ annual_salary_usd            │  3,500   │ 1,008  │ float64 │ 78800.0          │
│ manager_id                   │  3,382   │ 1,120  │ object  │ EMP00517         │
│ is_remote                    │  3,500   │   2    │  bool   │ True             │
│ employment_status            │  3,500   │   2    │ object  │ Active           │
╰──────────────────────────────┴──────────┴────────┴─────────┴──────────────────╯
                                  Memory: 1.61 MB

  ➤ Rows          3,500
  ➤ Columns          12

In [13]:
print("Sample data:")
E.sample(5)

Sample data:

,employee_id,department,country,job_level,gender,age,hire_date,tenure_days_as_of_2025_06_30,annual_salary_usd,manager_id,is_remote,employment_status
1081,EMP01082,Operations,UAE,Senior IC,Male,31,2020-12-18,1655,58500.0,EMP00318,False,Active
973,EMP00974,Operations,USA,Individual Contributor,Female,27,2023-11-17,591,60200.0,EMP02049,True,Active
475,EMP00476,Engineering,USA,Senior IC,Female,34,2020-02-20,1957,76300.0,EMP01517,False,Active
2177,EMP02178,Operations,India,Senior IC,Male,23,2023-05-02,790,41000.0,EMP02745,True,Active
2679,EMP02680,Engineering,Germany,Individual Contributor,Male,35,2019-04-15,2268,61200.0,EMP02485,True,Active

In [14]:
# convert hire_date to datetime format
E['hire_date'] = pd.to_datetime(E['hire_date'], errors='coerce')

In [ ]:
analyzer = DataQualityAnalyzer("datasets/employees.csv")
analyzer.run()

In [15]:
E['gender'] = E['gender'].fillna('Unknown')

In [17]:
missing_mgr = E[E['manager_id'].isna()]
print(missing_mgr['job_level'].value_counts())

job_level
Director          116
Senior Manager      1
Team Lead           1
Name: count, dtype: int64

### Cleaning data(hr_events dataset)

In [6]:
data_display = DataInfoDisplay(data=HR_E)   
data_display.display()

                          Data Info
╭─────────────┬──────────┬────────┬────────┬─────────────────╮
│ Column      │ Non-Null │ Unique │ Dtype  │ Sample          │
├─────────────┼──────────┼────────┼────────┼─────────────────┤
│ event_id    │  4,614   │ 4,614  │ object │ EVT000001       │
│ employee_id │  4,614   │ 2,574  │ object │ EMP00001        │
│ event_type  │  4,614   │   3    │ object │ Salary Increase │
│ event_date  │  4,614   │  909   │ object │ 2023-02-04      │
│ details     │  4,614   │  138   │ object │ +4.9%           │
╰─────────────┴──────────┴────────┴────────┴─────────────────╯
                        Memory: 1.29 MB

  ➤ Rows          4,614
  ➤ Columns           5

In [18]:
print("Simple data:")
HR_E.sample(5)

Simple data:

,event_id,employee_id,event_type,event_date,details
3039,EVT003040,EMP02323,Salary Increase,2024-11-27,+4.7%
792,EVT000793,EMP00613,Salary Increase,2024-01-20,+5.5%
2896,EVT002897,EMP02226,Salary Increase,2023-02-18,+6.4%
1680,EVT001681,EMP01292,Exit,2024-11-17,Voluntary - Personal Reasons
2848,EVT002849,EMP02189,Salary Increase,2025-06-09,+5.4%

In [19]:
# convert event_date to datetime format
HR_E['event_date'] = pd.to_datetime(HR_E['event_date'] , errors='coerce')

In [ ]:
analyzer = DataQualityAnalyzer("datasets/hr_events.csv")
analyzer.run()

### Cleaning data(performance_records dataset)

In [7]:
data_display = DataInfoDisplay(data=P)   
data_display.display()

                                 Data Info
╭───────────────────────────────┬──────────┬────────┬─────────┬────────────╮
│ Column                        │ Non-Null │ Unique │  Dtype  │ Sample     │
├───────────────────────────────┼──────────┼────────┼─────────┼────────────┤
│ performance_id                │  15,179  │ 15,179 │ object  │ PRF000001  │
│ employee_id                   │  15,179  │ 3,500  │ object  │ EMP00001   │
│ review_period                 │  15,179  │   5    │ object  │ 2024-H1    │
│ review_date                   │  15,179  │   5    │ object  │ 2024-06-30 │
│ performance_score_1to5        │  15,179  │  346   │ float64 │ 2.98       │
│ manager_rating_1to5           │  14,724  │   5    │ float64 │ 3.0        │
│ goals_total                   │  15,179  │   5    │  int64  │ 4          │
│ goals_achieved                │  15,179  │   7    │  int64  │ 3          │
│ goal_completion_rate_pct      │  15,179  │  691   │ float64 │ 64.8       │
│ peer_feedback_score_1to5      │  15,179  │  386   │ float64 │ 3.96       │
│ had_recent_training_last_180d │  15,179  │   2    │  bool   │ True       │
╰───────────────────────────────┴──────────┴────────┴─────────┴────────────╯
                               Memory: 4.04 MB

  ➤ Rows          15,179
  ➤ Columns           11

In [21]:
print("Sample data:")
P.sample(5)

Sample data:

,performance_id,employee_id,review_period,review_date,performance_score_1to5,manager_rating_1to5,goals_total,goals_achieved,goal_completion_rate_pct,peer_feedback_score_1to5,had_recent_training_last_180d
581,PRF000582,EMP00130,2023-H2,2023-12-31,3.44,3.0,4,3,63.5,4.09,False
5988,PRF005989,EMP01390,2025-H1,2025-06-30,5.00,5.0,6,6,95.5,5.00,True
15112,PRF015113,EMP03485,2024-H1,2024-06-30,2.98,3.0,5,3,51.7,3.47,True
3950,PRF003951,EMP00916,2025-H1,2025-06-30,3.91,3.0,3,3,90.6,3.08,True
4865,PRF004866,EMP01131,2023-H2,2023-12-31,3.64,4.0,7,6,80.1,4.23,False

In [22]:
# convert review_date to datetime format
P['review_date'] = pd.to_datetime(P['review_date'], errors='coerce')

In [ ]:
analyzer = DataQualityAnalyzer("datasets/performance_records.csv")
analyzer.run()

### Cleaning data(training_enrollments dataset)

In [8]:
data_display = DataInfoDisplay(data=TE)   
data_display.display()

                                 Data Info
╭───────────────────────────────┬──────────┬────────┬─────────┬────────────╮
│ Column                        │ Non-Null │ Unique │  Dtype  │ Sample     │
├───────────────────────────────┼──────────┼────────┼─────────┼────────────┤
│ enrollment_id                 │  20,132  │ 20,132 │ object  │ ENR000001  │
│ employee_id                   │  20,132  │ 3,369  │ object  │ EMP00001   │
│ program_id                    │  20,132  │   31   │ object  │ PRG013     │
│ enrollment_date               │  20,132  │  852   │ object  │ 2023-05-06 │
│ completion_status             │  20,132  │   3    │ object  │ Completed  │
│ completion_pct                │  20,132  │  965   │ float64 │ 93.7       │
│ completion_date               │  15,674  │  914   │ object  │ 2023-05-22 │
│ assessment_score              │  15,674  │  482   │ float64 │ 69.6       │
│ participant_satisfaction_1to5 │  16,478  │   41   │ float64 │ 4.3        │
╰───────────────────────────────┴──────────┴────────┴─────────┴────────────╯
                               Memory: 6.99 MB

  ➤ Rows          20,132
  ➤ Columns            9

In [23]:
print("Sample data:")
TE.sample(5)

Sample data:

,enrollment_id,employee_id,program_id,enrollment_date,completion_status,completion_pct,completion_date,assessment_score,participant_satisfaction_1to5
16193,ENR016194,EMP02822,PRG013,2025-04-24,Completed,90.2,2025-06-12,88.3,3.3
1619,ENR001620,EMP00282,PRG013,2023-11-06,Completed,98.0,2023-12-12,89.9,3.9
8867,ENR008868,EMP01539,PRG013,2024-10-11,Completed,100.0,2024-11-10,86.7,3.8
11518,ENR011519,EMP01998,PRG016,2024-01-24,Completed,93.1,2024-04-01,82.4,4.2
17383,ENR017384,EMP03031,PRG015,2023-09-07,Completed,97.1,2023-11-15,84.8,3.0

In [24]:
# convert completion_date and enrollment_date to datetime format
TE['completion_date'] = pd.to_datetime(TE['completion_date'], errors='coerce')
TE['enrollment_date'] = pd.to_datetime(TE['enrollment_date'], errors='coerce')

In [ ]:
analyzer = DataQualityAnalyzer("datasets/training_enrollments.csv")
analyzer.run()

### Cleaning data (training_enrollments dataset)

In [9]:
data_display = DataInfoDisplay(data=TP)   
data_display.display()

                                       Data Info
╭────────────────────────────────┬──────────┬────────┬─────────┬──────────────────────╮
│ Column                         │ Non-Null │ Unique │  Dtype  │ Sample               │
├────────────────────────────────┼──────────┼────────┼─────────┼──────────────────────┤
│ program_id                     │    31    │   31   │ object  │ PRG001               │
│ program_name                   │    31    │   31   │ object  │ Foundations of Peopl │
│ category                       │    31    │   6    │ object  │ Leadership           │
│ delivery_mode                  │    31    │   3    │ object  │ In-person            │
│ duration_hours                 │    31    │   18   │  int64  │ 24                   │
│ cost_per_participant_usd       │    31    │   24   │  int64  │ 950                  │
│ avg_instructor_rating_out_of_5 │    31    │   27   │ float64 │ 4.24                 │
│ is_mandatory                   │    31    │   2    │  bool   │ False                │
╰────────────────────────────────┴──────────┴────────┴─────────┴──────────────────────╯
                                     Memory: 0.01 MB

  ➤ Rows          31
  ➤ Columns        8

In [ ]:
analyzer = DataQualityAnalyzer("datasets/training_enrollments.csv")
analyzer.run()

In [ ]:
analyzer = DataQualityAnalyzer("datasets/training_programs.csv")
analyzer.run()